Repository realliance/madd2, pull requests merged in 2020-08, with the labels that each got.

#4 Contribution Resources
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: documentation

#5 Component Heap templated arguments
  include/component_heap.h
  include/types.h
  src/component_heap.cpp
  src/component_heap_iterator.cpp
  tests/component_heap.test.cpp
  tests/component_heap_iterator.test.cpp
Labels: enhancement

#3 Modify issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement-suggestion.md
Labels: documentation

#6 CI testing on g++
  .github/workflows/prvalidation.yml
Labels: enhancement

#7 Added ChristopherJMiller to mailmap and reviewer list
  .github/reviewer_config.yml
  .mailmap
Labels: documentation, enhancement

#8 Added testing for compiling and unit test passing in production
  .github/workflows/prvalidation.yml
Labels: enhancement
